openapi: 3.0.3
info:
  title: Particulate Matter API
  description: Particulate Matter API
  version: 1.0.0
servers:
  - url: 'http://localhost:8082/api/v1'
paths:
  /p10/{timestamp}:
    get:
      parameters:
        - in: path
          name: timestamp
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticulateMatterResponse'
components:
  schemas:
    ParticulateMatterResponse:
      type: object
      properties:
        value:
          type: number
        type:
          type: string

